config/routes.rb
Rails.application.routes.draw do

  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      :registrations => 'users/registrations',
      :passwords => 'users/passwords',
    }
  end

  get 'users/my' => 'users#my'
  get 'users/export-words' => 'users#export_words'
  get 'users/export-users' => 'users#export_users'
  get 'users' => 'users#index',as: 'users'
  get 'users/:id' => 'users#show',as: 'show_user'
  get 'users/:id/edit' => 'users#edit',as: 'edit_user' 
  patch 'users/:id/edit' => 'users#update',as: 'user' 

  get 'words/edit/section/:section_no' => 'words#words_edit',as: 'words_edit_section'
  get 'test/words/' => 'words#words_test',as: 'words_view2_section'
  get 'words/help' => 'words#help',as: 'words_help'

  resources :words do
    collection do
      get :search
    end
  end

  post    'ajax/words' => 'words#ajax_words_create'
  patch   'ajax/words' => 'words#ajax_words_update'
  put   'ajax/words' => 'words#ajax_words_update'
  delete  'ajax/words' => 'words#ajax_words_delete'
  post    'ajax/words/fav' => 'words#fav'

  get 'terms-of-use' =>'documents#terms'

  root to: 'words#index'
  get '*anything' => 'errors#routing_error'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:login]

	attr_accessor :login
	
	validates :username,
	  uniqueness: { case_sensitive: :false },
	  length: { minimum: 4, maximum: 20 },
	  format: { with: /\A[a-z0-9]+\z/, message: "ユーザー名は半角英数字です"}

  validates :role,
    inclusion:{
      in: ["viewer","editor","manager"]
    }

  has_and_belongs_to_many :words


	def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions.to_h).first
    end
  end


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end
   def create
    self.resource = resource_class.send_confirmation_instructions(resource_params)

    logger.debug resource
    # self.resource = User.where(:email => resource_params['email']).send_confirmation_instructions(resource_params)

    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_resending_confirmation_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end
  def create
    # logger.debug '**********************************************************'
    # logger.debug resource_params
    # logger.debug resource_params['email']
    # self.resource = resource_class.send_reset_password_instructions(resource_params)
    self.resource = User.where(:email => resource_params['email']).send_reset_password_instructions(resource_params)


    logger.debug self.resource.inspect
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	@@superuser_usename = 'kumassy'
  before_action :check_superuser,only: [:show,:edit,:update,:export_words,:export_users]
	before_action :check_manager,only: [:index]
  before_action :set_user,only:[:show,:edit,:update]

  def index
    @users = User.all
  end
 
  def show
    # @user.words << Word.where(hinshi: 'noun')
    # @user.save
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'user was successfully updated.'
    else
     render :edit
   end
  end

  def my
  end

  def export_words
    @words = Word.all
  end

  def export_users
    @users = User.all
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username,:email,:commitment,:role)
    end

		def check_superuser
			# logger.debug current_user.username
			# logger.debug @@superuser_usename
			unless (current_user.username == @@superuser_usename )
				raise Forbidden
			end
		end
    def check_manager
      # logger.debug current_user.username
      # logger.debug @@superuser_usename
      unless (current_user.username == @@superuser_usename ) || ( current_user.role == 'manager')
        raise Forbidden
      end
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div id="users">
<section class="mdl-shadow--2dp">

<h2>Edit User: <%= @user.username %></h2>

<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label 'メールアドレス' %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :commitment %><br />
    <%= f.text_field :commitment %>
  </div>

  <div class="field">
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
  <div class="action">
  	<%= link_to "戻る",show_user_path(@user.id) %>
  </div>
<% end %>
</section>
</div>

app/views/users/index.html.erb
<div id="users">
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% provide(:title, 'All users') %>
<h1>All users</h1>

<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
	<thead>
		<tr>
			<th class="mdl-data-table__cell--non-numeric">id</th>
			<th class="mdl-data-table__cell--non-numeric">email</th>
			<th class="mdl-data-table__cell--non-numeric">username</th>
			<th class="mdl-data-table__cell--non-numeric">role</th>
			<th class="mdl-data-table__cell--non-numeric">commitment</th>
			<th class="mdl-data-table__cell--non-numeric">sign_in_count</th>
			<th class="mdl-data-table__cell--non-numeric">current_sign_in_at</th>
			<th class="mdl-data-table__cell--non-numeric">last_sign_in_at</th>
			<th class="mdl-data-table__cell--non-numeric">confirmed_at</th>
			<th class="mdl-data-table__cell--non-numeric">confirmation_sent_at</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td class="mdl-data-table__cell--non-numeric"><%= user.id %></td>
			<td class="mdl-data-table__cell--non-numeric"><%= user.email %></td>
		    <td class="mdl-data-table__cell--non-numeric">
		      <%= link_to user.username, {action: :show,id: user.id} %>
		    </td>
		    <td class="mdl-data-table__cell--non-numeric"><%= user.role %></td>
		    <td class="mdl-data-table__cell--non-numeric"><%= user.commitment %></td>
		    <td class="mdl-data-table__cell--non-numeric"><%= user.sign_in_count %></td>
		    <td class="mdl-data-table__cell--non-numeric"><%= user.current_sign_in_at.to_time unless user.current_sign_in_at.nil? %></td>
		    <td class="mdl-data-table__cell--non-numeric"><%= user.last_sign_in_at.to_time unless user.last_sign_in_at.nil?%></td>
		    <td class="mdl-data-table__cell--non-numeric"><%= user.confirmed_at.to_time unless user.confirmed_at.nil?%></td>
		    <td class="mdl-data-table__cell--non-numeric"><%= user.confirmation_sent_at.to_time unless user.confirmation_sent_at.nil?%></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/users/my.html.erb
<div id="users">
<% provide(:title, 'MyPage') %>

<section class="mdl-shadow--2dp">
<h1>マイページ</h1>
	<section>
		<h3>アカウントを編集</h3>
		<p>メールアドレスやパスワードを変更できます
		<%= link_to "変更", edit_user_registration_path, method: :get,class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
		</p>
	</section>
	<section>
		<h3>ふぁぼ りすと</h3>
		<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
			<thead>
				<tr>
			        <!-- <th class="mdl-data-table__cell--non-numeric">id</th> -->
			        <th class="mdl-data-table__cell--non-numeric">ピンイン</th>
			        <th class="mdl-data-table__cell--non-numeric">簡体字</th>
			        <th class="mdl-data-table__cell--non-numeric">意味</th>
			        <th class="mdl-data-table__cell--non-numeric">品詞</th>
			        <th>ページ</th>
			        <th>章</th>
			    </tr>
		    </thead>
		    <tbody>
			    <% current_user.words.each do |word| %>
			    <tr>
			    	<!-- <td class="mdl-data-table__cell--non-numeric"><%= word.id %></td> -->
			    	<td class="mdl-data-table__cell--non-numeric"><%= word.pinnin %></td>
			        <td class="mdl-data-table__cell--non-numeric"><%= word.kantaiji %></td>
			        <td class="mdl-data-table__cell--non-numeric"><%= word.imi %></td>
			        <td class="mdl-data-table__cell--non-numeric"><%= get_styled_hinshi word.hinshi %></td>
			        <td><%= word.page %></td>
			        <td><%= word.section %></td>
			    </tr>
			    <% end %>
		    </tbody>
		    
		</table>
	</section>
</section>
</div>

app/views/users/show.html.erb
<div id="users">
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<% provide(:title, @user.username) %>
<section class="mdl-shadow--2dp">
<h1>My page (<%= @user.username %>)</h1>
	<h3>Profile</h3>
	<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
		<tr>
			<th>id</th>
			<td><%= @user.id %></td>
		</tr>
		<tr>
			<th>username</th>
			<td><%= @user.username %></td>
		</tr>
		<tr>
			<th>email</th>
			<td><%= @user.email %></td>
		</tr>
		<tr>
			<th>sign_in_count</th>
			<td><%= @user.sign_in_count %></td>
		</tr>
	</table>
</section>

<section class="mdl-shadow--2dp">
	<h3>Fav List</h3>
	<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
		<thead>
			<tr>
		        <th class="mdl-data-table__cell--non-numeric">id</th>
		        <th class="mdl-data-table__cell--non-numeric">pinnin</th>
		        <th class="mdl-data-table__cell--non-numeric">kantaiji</th>
		        <th class="mdl-data-table__cell--non-numeric">imi</th>
		        <th class="mdl-data-table__cell--non-numeric">hinshi</th>
		        <th>page</th>
		        <th>section</th>
		    </tr>
	    </thead>
	    <tbody>
		    <!-- yield -->
		    <% @user.words.each do |word| %>
		    <tr>
		    	<td class="mdl-data-table__cell--non-numeric"><%= word.id %></td>
		    	<td class="mdl-data-table__cell--non-numeric"><%= word.pinnin %></td>
		        <td class="mdl-data-table__cell--non-numeric"><%= word.kantaiji %></td>
		        <td class="mdl-data-table__cell--non-numeric"><%= word.imi %></td>
		        <td class="mdl-data-table__cell--non-numeric"><%= word.hinshi %></td>
		        <td><%= word.page %></td>
		        <td><%= word.section %></td>
		    </tr>
		    <% end %>
	    </tbody>
	    
	</table>
	<div class="action">
	  	<%= link_to "edit",user_path(@user.id) %>
	  </div>
</section>

</div>