config/routes.rb
Rails.application.routes.draw do

  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      :registrations => 'users/registrations',
      :passwords => 'users/passwords',
    }
  end

  get 'users/my' => 'users#my'
  get 'users/export-words' => 'users#export_words'
  get 'users/export-users' => 'users#export_users'
  get 'users' => 'users#index',as: 'users'
  get 'users/:id' => 'users#show',as: 'show_user'
  get 'users/:id/edit' => 'users#edit',as: 'edit_user' 
  patch 'users/:id/edit' => 'users#update',as: 'user' 

  get 'words/edit/section/:section_no' => 'words#words_edit',as: 'words_edit_section'
  get 'test/words/' => 'words#words_test',as: 'words_view2_section'
  get 'words/help' => 'words#help',as: 'words_help'

  resources :words do
    collection do
      get :search
    end
  end

  post    'ajax/words' => 'words#ajax_words_create'
  patch   'ajax/words' => 'words#ajax_words_update'
  put   'ajax/words' => 'words#ajax_words_update'
  delete  'ajax/words' => 'words#ajax_words_delete'
  post    'ajax/words/fav' => 'words#fav'

  get 'terms-of-use' =>'documents#terms'

  root to: 'words#index'
  get '*anything' => 'errors#routing_error'

end

app/models/word.rb
class Word < ActiveRecord::Base
	# accepts_nested_attributes_for :words, allow_destroy: true 
	has_and_belongs_to_many :users

	validates :pinnin,
		presence: true
	validates :rawpinnin,
		presence: true
	validates :styledpinnin,
		presence: true
	validates :kantaiji,
		presence: true
	validates :hinshi,
		inclusion:{
			in: ["noun","verb","adjective","adverb", "preposition","number","conjunction", "exclamation", "rigoushi","idiom","auxiliary_verb","uncategorized", "other"]
		}
	validates :page,
		numericality:{
			only_integer: true
		}
	validates :section,
		numericality:{
			only_integer: true
		}


end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_action :set_hinshis, only: [:index,:search,:words_edit]
  before_action :check_commitment,only: [:words_test]
  before_action :check_role,except:[:fav,:index,:show,:words_test,:search,:help]
  # GET /words
  # GET /words.json
  def index
    @words = Word.all
    @words = @words.order(' page ASC')

    # @words = @words.where(id: current_user.words)

    # @selected_hinshis = @hinshis

    
    render 'index-printable' ,:layout => 'printable' if params[:printable] == 'true'
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)
    
    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  def words_edit
    @section = params[:section_no]
    @words = Word.where(section: @section)

    # sort by id and page
    @words = @words.order(' page ASC')
  end

  def view
    @from = params[:from]
    unless @from.in?(['pinnin','kantaiji','imi'])
      render text: "URLパラメータが存在しないか、不正です。from=pinnin | kantaiji | imi,[to=pinnin | kantaiji | imi]"
    end
    
    @to = params[:to]
    unless @to.in?(['pinnin','kantaiji','imi'])
      @to = 'all'
    end

    @section = params[:section_no]
    @words = Word.where(section: @section)
  end

  def words_test
    @words= Word.all
    

    @from = params[:from]
    unless @from.in?(['pinnin','kantaiji','imi'])
      render text: "URLパラメータが存在しないか、不正です。from=pinnin | kantaiji | imi,[to=pinnin | kantaiji | imi]"
    end
    
    @to = params[:to]
    unless @to.in?(['pinnin','kantaiji','imi'])
      @to = 'all'
    end

    @section = params[:section]
    if @section.nil?
      @section = (12..20).to_a
    end
    @words = @words.where(section: @section)

    @isonlyfav = params[:isonlyfav]
    if @isonlyfav == 'true'
      @words = @words.where(id: current_user.words)
    end

    # sort
    @words = @words.order(' page ASC')


    @doShuffle = params[:doshuffle]
    if @doShuffle == 'true'
      @words = @words.shuffle
    end

    render :layout => 'onsen'
  end

  def ajax_words_create
    logger.debug 'ajax!'
    @word = Word.new(word_params)
    
    if @word.save
      current_user.increment(:commitment)
      current_user.save
      render json: @word
      return
    else
      render json: @word.errors, status: :unprocessable_entity
      return
    end
  end

  def ajax_words_update
    @word = Word.find(ajax_word_params[:id])
    
    if @word.update(word_params)
      current_user.increment(:commitment)
      current_user.save
      render json: @word
      return
    else
      render json: @word.errors, status: :unprocessable_entity
      return
    end
  end

  def ajax_words_delete
    logger.debug 'delete!!!'
    @word = Word.find(ajax_word_params[:id])
    
    if @word.destroy
      render json: @word
      return
    else
      render json: @word.errors, status: :unprocessable_entity
      return
    end
  end

  def fav
    @id = params[:word][:id]
    word = Word.where(id: @id)
    # user = User.where(id: params[:user_id])
    user = current_user

    if user.words.exists? word
      user.words.destroy word
      @new_fav_link = '☆'
    else
      user.words << word
      @new_fav_link = '★'
    end
  end

  def help
  end


  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    # TODO: エスケープ処理
    @query = params[:q]
    @words = Word.where("pinnin
     like(:qu) OR kantaiji like(:qu) OR imi like(:qu)",{qu: "%#{@query}%"})

    
    unless params[:hinshis].nil?
      @selected_hinshis = params[:hinshis][:value]
      @words = @words.where(hinshi: @selected_hinshis)
    end

    @isonlyfav = false
    unless params[:isonlyfav].nil?
      @isonlyfav = params[:isonlyfav]
      @words = @words.where(id: current_user.words)
    end

    @words = @words.order(' page ASC')


    if params[:printable] == 'true'
      render 'index-printable' ,:layout => 'printable' 
    else 
      render :index
    end      
    # render text: @words.size
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    def set_hinshis
      @selected_hinshis =[]
      @hinshis = ["noun","verb","adjective","adverb", "preposition","number","conjunction", "exclamation", "rigoushi","idiom", "auxiliary_verb","other","uncategorized"]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      # params.require(:word).permit(:pinnin, :kantaiji, :hinshi, :imi, :rigoushi, :page, :section)
      params.require(:word).permit(:pinnin,:styledpinnin,:rawpinnin, :kantaiji, :hinshi, :imi, :page, :section)
    end

    def ajax_word_params
      # params.require(:word).permit(:id,:pinnin, :kantaiji, :hinshi, :imi, :rigoushi, :page, :section)
      params.require(:word).permit(:id,:pinnin,:styledpinnin,:rawpinnin, :kantaiji, :hinshi, :imi, :page, :section)
    end

    # def word_id
    #   params.require(:word).permit(:id)
    # end
    def check_commitment
      @required_commitment = -1
      if current_user.commitment < @required_commitment
        render 'not-enough-commitment',:layout => 'onsen'
      end
    end

    def check_role
      unless (current_user.role == 'editor') || ( current_user.role == 'manager')
        raise Forbidden
      end
    end
end

app/helpers/words_helper.rb
module WordsHelper
	# def get_styled_hinshi(h)
	# 	case h
	# 	when 'noun'
	# 		'名詞'
	# 	when 'verb'
	# 		'動詞'
	# 	when 'rigoushi'
	# 		'離合詞'
	# 	end
	# end

	def get_styled_page(p)
		if p
			p.to_s+'ページ'
		end
	end

	def get_styled_section(s)
		if s
			s.to_s+'章'
		end
	end

	def get_view_header(s)
		case s
		when 'pinnin'
			'ピンイン'
		when 'kantaiji'
			'簡体字'
		when 'imi'
			'意味'
		when 'all'
			'全部'
		end
	end
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pinnin %><br>
    <%= f.text_field :pinnin %>
  </div>
  <div class="field">
    <%= f.label :kantaiji %><br>
    <%= f.text_field :kantaiji %>
  </div>
  <div class="field">
    <%= f.label :hinshi %><br>
    <%= f.text_field :hinshi %>
  </div>
  <div class="field">
    <%= f.label :imi %><br>
    <%= f.text_field :imi %>
  </div>
  <div class="field">
    <%= f.label :page %><br>
    <%= f.text_field :page %>
  </div>
  <div class="field">
    <%= f.label :section %><br>
    <%= f.text_field :section %>
  </div>
  <div class="actions">
    <%= submit_tag  %>
  </div> 
<% end %>

app/views/words/_multiform.html.erb
  <%= simple_nested_form_for(@word) do |m| %>
    <%= m.input :title, label: 'タイトル' %>
        <table id='tasks'>
            <%= m.simple_fields_for :steps do |s| %>
                <tr class='steps-field'>
                    <td>
                        <%= s.text_area :content %>
                    </td>
                    <td>
                        <%= s.link_to_remove '削除' %>
                    </td>
                </tr>
            <% end %>
        </table>
        <%= m.submit %>
        <%= m.link_to_add "追加", :steps, data: { target: '#tasks'} %>
<% end %>





<%= form_tag({action: :create_multi},id: :new_multi) do %>
<div class="field">
<table>
    <tr>
        <th>pinnin</th>
        <th>kantaiji</th>
        <th>hinshi</th>
        <th>imi</th>
        <th>rigoushi</th>
        <th>page</th>
        <th>section</th>
    </tr>
    <tr>
        <td><%= text_field :word, :pinnin %></td>
        <td><%= text_field :word, :kantaiji %></td>
        <td><%= text_field :word, :hinshi %></td>
        <td><%= text_field :word, :imi %></td>
        <td><%= check_box :word, :rigoushi %></td>
        <td><%= text_field :word, :page %></td>
        <td><%= text_field :word, :section %></td>
    </tr>
</table>
<%= submit_tag '送信' %>
</div>
<% end %>

app/views/words/_multiform3.html.erb
<div class="field">
<%= form_tag({action: :create_multi},id: :create,method: :post) do %>

<table>
    <tr>
        <th>pinnin</th>
        <th>kantaiji</th>
        <th>hinshi</th>
        <th>imi</th>
        <th>rigoushi</th>
        <th>page</th>
        <th>section</th>
    </tr>

    <% @words.each_with_index do |word,index| %>
      <%= form_for word do |f| %>
        <tr>
            <td><%= f.text_field :pinnin , name: "word[#{index}][pinnin]"%></td>
            <td><%= f.text_field :kantaiji , name: "word[#{index}][kantaiji]"%></td>
            <td><%= f.text_field :hinshi , name: "word[#{index}][hinshi]"%></td>
            <td><%= f.text_field :imi , name: "word[#{index}][imi]"%></td>
            <td><%= f.check_box :rigoushi , name: "word[#{index}][rigoushi]"%></td>
            <td><%= f.text_field :page , name: "word[#{index}][page]"%></td>
            <td><%= f.text_field :section , name: "word[#{index}][section]"%></td>
        </tr>
      <% end %>
    <% end %>
</table>


<%= submit_tag('送信',name: nil) %>
<% end %>
</div>

app/views/words/ajax_test.html.erb
<div id="ajax-test">
	<table>
		<tbody>
			<tr>
		        <th>pinnin</th>
		        <th>kantaiji</th>
		        <th>hinshi</th>
		        <th>imi</th>
		        <th>rigoushi</th>
		        <th>page</th>
		        <th>section</th>
		    </tr>
		    <!-- yield -->
	    </tbody>
	    
	</table>
	<input type="button" value="追加" id="ajax-button">
	<input type="button" value="submit" id="ajax-submit">

</div>

app/views/words/fav.js.erb
$("#fav-word-id-<%= @id %>").html(
	"<%= escape_javascript(render 'fav') %>"
);

app/views/words/help.html.erb
<div id="words">
	<h3>ショートカットキー</h3>
	<h5>新規行を追加</h5>
	Ctrl + d 【Mac】| Ctrl + q 【windows】 | Alt + d | Alt + q
	<h5>submit (サーバーに反映)</h5>	
	Ctrl + Enter | Alt + Enter | Shift + Enter
	
	<h5>その他</h5>
	品詞は途中まで打つか、そのまま↓キーを押して選択→Enter<br>簡体字は↓キーで選択→Enter
	
	<h3>入力値の制約</h3>
	<p>ピンイン：必須 | 簡体字：必須 | 品詞：[名詞：noun,動詞：verb,形容詞：adjective,副詞：adverb,前置詞：preposition,数詞：number,接続詞：conjunction,間投詞：exclamation,離合詞：rigoushi,熟語：idiom,助動詞：auxiliary_verb,その他：other,未分類：uncategorized] | ページ：必須 (数値) | 章：必須 (数値)</p>
	
	<h3>声調つき文字の入力</h3>
	<table class="mdl-data-table mdl-js-data-table">
		<tbody>
			<tr>
				<td>a1→ā</td>
				<td>a2→á</td>
				<td>a3→ǎ</td>
				<td>a4→à</td>
			</tr>
			<tr>
				<td>e1→ē</td>
				<td>e2→é</td>
				<td>e3→ě</td>
				<td>e4→è</td>
			</tr>
			<tr>
			    <td>i1→ī</td>
			    <td>i2→í</td>
			    <td>i3→ǐ</td>
			    <td>i4→ì</td>
		    </tr>
		    <tr>
			    <td>o1→ō</td>
			    <td>o2→ó</td>
			    <td>o3→ǒ</td>
			    <td>o4→ò</td>
		    </tr>
		    <tr>
			    <td>u1→ū</td>
			    <td>u2→ú</td>
			    <td>u3→ǔ</td>
			    <td>u4→ù</td>
		    </tr>
		    <tr>
			    <td>v1→ǖ</td>
			    <td>v2→ǘ</td>
			    <td>v3→ǚ</td>
			    <td>v4→ǜ</td>
		    </tr>
		    <tr>
		    	<td colspan="4">v→ü</td>
		    </tr>
	    </tbody>
	    
	</table>
	<h3>サーバーへの反映</h3>
	<ul>
		<li>行の新規追加、項目の変更をすると「同期」項目が赤色になります。「同期」項目が赤色の場合、項目の変更がサーバーに反映されていないことを表します。</li>
		<li>「submit」ボタンを押し、サーバーに項目の変更が反映されると、「同期」項目が緑色になります。</li>
		<li>行の削除は「削除」ボタンを押しても「同期」が赤色になりませんが、そのままではサーバーに反映されません。削除をキャンセルするときは再度「削除」ボタンを押してください。削除を確定する場合は、「submit」ボタンを押してください。</li>
		<li>各行は基本的に上から同期されていきますが、ネットワークの状態によってたまに順番が入れ替わることがあります。そのため項目を新規追加したあとにページを再読み込みすると一部順番が入れ替わっていることがあります。</li>
	</ul>

	<h3>エラー</h3>
	<%= image_tag "error_unprocessable.png" ,:width => "400px"%>
	<p>「submit」ボタンを押したときに図のようなエラーが出る場合があります。この時は以下の原因が考えられます。</p>
	<ul>
		<li>入力値が上記「入力値の制約」を満たしていない</li>
		<li>単語を新規追加するときに、なんらかの項目からフォーカスを外していない</li>
	</ul>
	<p>単語をまとめて新規追加するときに最後の単語だけこのエラーが起きることがあります。その時には<strong style="color:red;">画面の空いているところをクリックして</strong>から再度「submit」ボタンを押してください。</p>
	<hr>
	<%= image_tag "error_not_found.png" ,:width => "400px"%>
	<p>このエラーは新規追加した項目に対して「削除」ボタンを押し、「submit」ボタンを押すと発生します。気にしないでください。</p>

</div>

app/views/words/index-printable.html.erb
<div id="words-printable">
  <div id="print-settings">
    <h3>印刷用ページ</h3>
    <label for="color-pinnin">文字色(ピンイン)</label>
    <input type="text" name="color-pinnin" value="#000000">
    <label for="color-kantaiji">文字色(簡体字)</label>
    <input type="text" name="color-kantaiji" value="#000000">
    <label for="color-imi">文字色(意味)</label>
    <input type="text" name="color-imi" value="#000000">
    <br>

    <label for="font-pinnin">大きさ(ピンイン)</label>
    <input type="text" name="font-pinnin" value="60">
    <label for="font-kantaiji">大きさ(簡体字)</label>
    <input type="text" name="font-kantaiji" value="60">
    <label for="font-imi">大きさ(意味)</label>
    <input type="text" name="font-imi" value="13">
    <br>

    <label for="toggle-hinshi">品詞を表示</label>
    <input type="checkbox" name="toggle-hinshi" checked>
    <label for="toggle-page">ページ数を表示</label>
    <input type="checkbox" name="toggle-page" checked>
    <label for="toggle-section">章を表示</label>
    <input type="checkbox" name="toggle-section" checked>

    <li>文字色は名前かカラーコードで指定 (例: pink,orange,#eee)</li>
    <li>大きさの単位はpx</li>
  </div>
<table>
  <thead>
    <tr>
      <th></th>
      <th>ピンイン</th>
      <th>簡体字</th>
      <th>意味</th>
      <th class="printable-hinshi">品詞</th>
      <th class="printable-page">ページ</th>
      <th class="printable-section">章</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td class="checkbox"><div class="td-inner">&nbsp;</div></td>
        <td class="printable-pinnin large"><div class="td-inner"><%= word.styledpinnin %></div></td>
        <td class="printable-kantaiji large kantaiji-font"><div class="td-inner"><%= word.kantaiji %></div></td>
        <td><div class="printable-imi td-inner"><%= word.imi %></div></td>
        <td class="printable-hinshi"><div class="td-inner"><%= get_styled_hinshi word.hinshi %></div></td>
        <td class="printable-page"><div class="td-inner"><%= word.page %></div></td>
        <td class="printable-section"><div class="td-inner"><%= word.section %></div></td>
        <!-- <td><%= link_to 'Show', word %></td> -->
        <!-- <td><%= link_to 'Edit', edit_word_path(word) %></td> -->
        <!-- <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Word', new_word_path %> -->
</div>

app/views/words/index.html.erb
<div id="words" class="mdl-shadow--2dp">
<h1>Listing Words</h1>

<section>
<h3>SearchBox</h3>
<%= form_tag({action: :search},id: :search,method: :get) do %>
  <div class="field">
    <%= label :q, "検索："%>
    <%= text_field_tag :q,@query %>
  </div>
  <div class="field">
    <% @hinshis.each do |hinshi| %>
      <%= label "hinshis" ,get_styled_hinshi(hinshi) %>
      <%= check_box_tag "hinshis[value][]" ,hinshi ,@selected_hinshis.include?(hinshi)%>
      |
    <% end %>
  </div>
  <div class="field">
    <%= label :isonlyfav ,'ふぁぼのみ' %>
    <%= check_box_tag :isonlyfav ,true ,@isonlyfav%>
  </div>
    <%= submit_tag('検索',name: nil) %>
  <% # http://www.mk-mode.com/octopress/2014/06/11/rails-commit-utf8-param-of-submit-tag/ %>
<% end %>
</section>


<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">ふぁぼ</th>
      <th class="mdl-data-table__cell--non-numeric">ピンイン</th>
      <th class="mdl-data-table__cell--non-numeric">ピンイン(raw)</th>
      <th class="mdl-data-table__cell--non-numeric">ピンイン(styled)</th>
      <th class="mdl-data-table__cell--non-numeric">簡体字</th>
      <th class="mdl-data-table__cell--non-numeric">品詞</th>
      <th class="mdl-data-table__cell--non-numeric">意味</th>
      <th>ページ</th>
      <th>章</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td id="fav-word-id-<%= word.id %>" class="mdl-data-table__cell--non-numeric">
          <% if current_user.words.exists? word.id %>
            <%= link_to '★',{action: :fav,word:{id: word.id}},method: :post,remote: true %>
          <% elsif %>
            <%= link_to '☆',{action: :fav,word:{id: word.id}},method: :post,remote: true %>
          <% end %>
        </td>
        <td class="mdl-data-table__cell--non-numeric"><%= word.pinnin %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= word.rawpinnin %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= word.styledpinnin %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= word.kantaiji %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= get_styled_hinshi word.hinshi %></td>
        <td class="mdl-data-table__cell--non-numeric"><%= word.imi %></td>
        <td><%= word.page %></td>
        <td><%= word.section %></td>
        <!-- <td><%= link_to 'Show', word %></td> -->
        <!-- <td><%= link_to 'Edit', edit_word_path(word) %></td> -->
        <!-- <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Word', new_word_path %> -->
</div>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/new_multi.html.erb
<h1>New Word</h1>

<%= render 'multiform3' %>

<%= link_to 'Back', words_path %>

app/views/words/not-enough-commitment.html.erb
<div id="onsen">

<!-- <ons-sliding-menu var="app.menu" menu-page="menu.html" main-page="page1.html" max-slide-distance="200px" type="reveal" side="left"> -->
<!-- <ons-navigator var="globalNavi"> -->
<!--   <ons-navigator var="navi" page="page1.html">
  </ons-navigator>
 -->
 <!-- </ons-navigator>-->

<!-- </ons-sliding-menu> -->

<ons-navigator var="navi" page="page1.html"></ons-navigator>


<ons-template id="page1.html" class="view-page-template">
  <ons-page>
    <ons-toolbar>
      <div class="center">Error</div>
    </ons-toolbar>
    <div style="text-align: center">
      <h1>単語テストを利用できません</h1>
      <p>単語テストを利用するには、単語データベースへ少なくとも<%= @required_commitment %>個の単語の追加する必要があります。</p>
    </div>
  </ons-page>
</ons-template>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pinnin:</strong>
  <%= @word.pinnin %>
</p>

<p>
  <strong>Kantaiji:</strong>
  <%= @word.kantaiji %>
</p>

<p>
  <strong>Hinshi:</strong>
  <%= @word.hinshi %>
</p>

<p>
  <strong>Imi:</strong>
  <%= @word.imi %>
</p>


<p>
  <strong>Page:</strong>
  <%= @word.page %>
</p>

<p>
  <strong>Section:</strong>
  <%= @word.section %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>

app/views/words/view.html.erb
<div id="view">
	<div class="desc"><%= @section %>章<br><%= get_view_header @from %>→<%= get_view_header @to %></div>
	<table>
		<thead>
			<tr>
				<th class="fav">Fav</th>	
		        <th class="from"><%= get_view_header @from %></th>
		        <th class="to"><%= get_view_header @to %></th>
		    </tr>
	    </thead>
		<tbody>
		    <!-- yield -->
		    <% @words.each.with_index(1) do |word,index| %>
		    <tr data-id="<%= word.id %>">
			    <td id="fav-word-id-<%= word.id %>">
		          <% if current_user.words.exists? word.id %>
		            <%= link_to '★',{action: :fav,word:{id: word.id}},method: :post,remote: true %>
		          <% elsif %>
		            <%= link_to '☆',{action: :fav,word:{id: word.id}},method: :post,remote: true %>
		          <% end %>
		        </td>
			    <% case @from %>
				<% when "pinnin" %>
			        <td class="from"><%= word.styledpinnin %></td>
		        <% when "kantaiji" %>
			        <td class="from"><%= word.kantaiji %></td>
		        <% when "imi" %>
			        <td class="from"><%= word.imi %></td>
		        <% end %>

		        <% case @to %>
				<% when "pinnin" %>
			        <td class="to"><div class="to-wrapper hidden"><%= word.styledpinnin %></div></td>
		        <% when "kantaiji" %>
			        <td class="to"><div class="to-wrapper hidden"><%= word.kantaiji %></div></td>
		        <% when "imi" %>
			        <td class="to"><div class="to-wrapper hidden"><%= word.imi %></div></td>
			    <% else %>
				    <td class="to">
					    <div class="to-wrapper hidden">
						    <div class="pinnin-kantaiji">
							    <span class="pinnin">
								    <%= word.styledpinnin %>
							    </span>
							    <span class="kantaiji">
								    | <%= word.kantaiji %>
							    </span>
						    </div>
						    <div class="hinshi-imi">
							    <span class="hinshi">
								    【<%= get_styled_hinshi word.hinshi %>】
								</span>
							    <span class="imi">
								    <%= word.imi %>
								</span>
							</div>
							<div class="page-section">
								<span class="page">
								    <%= get_styled_page word.page %> | 
							    </span>
							    <span class="section">
								    <%= get_styled_section word.section %>
							    </span>
						    </div>
					    </div>
				    </td>	
		        <% end %>
		    </tr>
		    <% end %>
	    </tbody>
	    
	</table>

</div>