config/routes.rb
Rails.application.routes.draw do

  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      :registrations => 'users/registrations',
      :passwords => 'users/passwords',
    }
  end

  get 'users/my' => 'users#my'
  get 'users/export-words' => 'users#export_words'
  get 'users/export-users' => 'users#export_users'
  get 'users' => 'users#index',as: 'users'
  get 'users/:id' => 'users#show',as: 'show_user'
  get 'users/:id/edit' => 'users#edit',as: 'edit_user' 
  patch 'users/:id/edit' => 'users#update',as: 'user' 

  get 'words/edit/section/:section_no' => 'words#words_edit',as: 'words_edit_section'
  get 'test/words/' => 'words#words_test',as: 'words_view2_section'
  get 'words/help' => 'words#help',as: 'words_help'

  resources :words do
    collection do
      get :search
    end
  end

  post    'ajax/words' => 'words#ajax_words_create'
  patch   'ajax/words' => 'words#ajax_words_update'
  put   'ajax/words' => 'words#ajax_words_update'
  delete  'ajax/words' => 'words#ajax_words_delete'
  post    'ajax/words/fav' => 'words#fav'

  get 'terms-of-use' =>'documents#terms'

  root to: 'words#index'
  get '*anything' => 'errors#routing_error'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Words</title>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.indigo-pink.min.css">
	<script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	

</head>
<body>
	<% if user_signed_in? && false %>
	<div id="login-status">
		<div class="mdl-card mdl-shadow--2dp">
			<div class="mdl-card__title">
				<h2 class="mdl-card__title-text"></h2>
			</div>
			<div class="mdl-card__supporting-text">
				<p><%= current_user.username %>としてログインしています</p>
			</div>
			<div class="mdl-card__actions mdl-card--border">
				<%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
			</div>
			<div class="mdl-card__actions mdl-card--border">
				<%= link_to "マイページ",users_my_path, method: :get,class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
			</div>
		</div>	
	</div>
	<% end %>
		
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	<%= yield %>

	<footer class="mdl-mega-footer">
		<div class="mdl-mega-footer--middle-section">
			<% if user_signed_in? && (current_user.role == 'manager' || current_user.role == 'editor' )%>
			<div class="mdl-mega-footer--drop-down-section">
				<h1 class="mdl-mega-footer--heading">単語を登録する</h1>
				<ul class="mdl-mega-footer--link-list">
					<% sections = (12..20).to_a %>
					<% sections.each do |section| %>
		                <li><%= link_to "#{section}章",words_edit_section_path(section_no: section),method: :get %></li>
	                <% end %>
				</ul>
			</div>
            <% end %>
			<div class="mdl-mega-footer--drop-down-section">
				<h1 class="mdl-mega-footer--heading">単語をテスト (ピンインから)</h1>
				<ul class="mdl-mega-footer--link-list">
	                <% sections = (12..20).to_a %>
					<% sections.each do |section| %>
		                <li><%= link_to "#{section}章",words_view2_section_path(section: section,from: 'pinnin'),method: :get %></li>
	                <% end %>
				</ul>
			</div>
			<div class="mdl-mega-footer--drop-down-section">
				<h1 class="mdl-mega-footer--heading">単語をテスト (簡体字から)</h1>
				<ul class="mdl-mega-footer--link-list">
	                <% sections = (12..20).to_a %>
					<% sections.each do |section| %>
		                <li><%= link_to "#{section}章",words_view2_section_path(section: section,from: 'kantaiji'),method: :get %></li>
	                <% end %>
				</ul>
			</div>
			<div class="mdl-mega-footer--drop-down-section">
				<h1 class="mdl-mega-footer--heading">その他</h1>
				<ul class="mdl-mega-footer--link-list">
	                <li><%= link_to '全ての単語', words_path %></li>
					<% if user_signed_in? && current_user.role == 'manager' %>
						<li><%= link_to 'ユーザーリスト', users_path %></li>
	                <% end %>
	                <li><%= link_to '利用条件', terms_of_use_path %></li>
	                <li><%= link_to '単語登録のヘルプ', words_help_path %></li>
				</ul>
			</div>
		</div>
		<% if user_signed_in? %>
		<div class="mdl-mega-footer--bottom-section">
            <div class="mdl-logo">
              <%= current_user.username %>としてログインしています
            </div>
            <ul class="mdl-mega-footer--link-list">
				<li><%= link_to 'マイページ', users_my_path,class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %></li>
				<li><%= link_to 'アカウントの編集', edit_user_registration_path,class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %></li>
				<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %></li>
            </ul>
		</div>
		<% end %>
	</footer>

</body>
</html>

app/views/layouts/onsen.html.erb
<!DOCTYPE html>
<html lang="ja" ng-app="app" ng-csp>
<head>
	 <meta charset="utf-8" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />

    <!-- JS dependencies (order matters!) -->
    <!--<script src="../assets/platformOverrides.js"></script>-->
    <!--<script src="../../../vendor/assets/angular/angular.js"></script>-->
    <!--<script src="onsen/js/onsenui.js"></script>-->

    <!-- CSS dependencies -->
    <!--<link rel="stylesheet" href="onsen/css/onsenui.css" />-->
    <!--<link rel="stylesheet" href="onsen/css/onsen-css-components-blue-basic-theme.css" />-->

    <!-- CSP support mode (required for Windows Universal apps) -->
    <!--<link rel="stylesheet" href="angular/angular-csp.css" />-->
	

	<title>Word Test</title>


	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.indigo-pink.min.css">
	<script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	<script>
        var module = angular.module('app', ['onsen']);

        // module.controller('MyController', function($scope, $window) {
        //     $scope.go = function(demo) {
        //         $window.location.href = demo;
        //     };
        // });
    </script>
</head>
<body>
	<!-- Cordova reference -->
    <!--<script src="cordova.js"></script>-->
    <!--<script src="scripts/index.js"></script>-->
    <!-- -->
 
	<%= yield %>


</body>
</html>

app/views/layouts/printable.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>印刷用ページ</title>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.indigo-pink.min.css">
	<script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	

</head>
<body>
	<%= yield %>
</body>
</html>